apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: my-iot-cluster
servers: 1
image: rancher/k3s:latest
ports:
  - port: 8082:80
    nodeFilters:
      - loadbalancer
  - port: 30000:30000
    nodeFilters:
      - server:0
  - port: 30001:30001
    nodeFilters:
      - server:0
