apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ce
  namespace: gitlab
  labels:
    app: gitlab-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-ce
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        # add health checks
        livenessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 300  # GitLab takes time to start
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 10
        volumeMounts:
        - name: gitlab-storage
          mountPath: /var/opt/gitlab  # Persistent data storage path for GitLab
      volumes:
      - name: gitlab-storage
        persistentVolumeClaim:
          claimName: gitlab-pvc