apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 5Gi  # Define the storage capacity
  accessModes:
    - ReadWriteOnce  # Only one node can write at a time
  persistentVolumeReclaimPolicy: Retain  # Keep data even if PVC is deleted
  storageClassName: gitlab-storage
  hostPath:
    path: "/mnt/gitlab-data"  # Local storage path on the node (adjust as needed)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gitlab-storage

