Vagrant.configure("2") do |config|
    #Server Node
    config.vm.define "amiskiS" do |server_conf|
        server_conf.vm.box = "hashicorp/bionic64"
        server_conf.vm.box_version = "1.0.282"
        server_conf.vm.hostname = "Server"
        server_conf.vm.network "private_network", ip: "192.168.56.110"
        server_conf.vm.provider "virtualbox" do |vb|
            vb.name = "amiskiS"
            vb.memory = "2048"
            vb.cpus = 2
        end
        server_conf.vm.provision "shell", path: "./scripts/vm_setup.sh"
    end

end

  