# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Server Machine: fech-chaS
  config.vm.define "fech-chaS" do |fechS|
    fechS.vm.box = "ubuntu/jammy64"
    fechS.vm.box_version = "20241002.0.0"

    # check the box integrity
    fechS.vm.box_download_checksum = "f322c39945bd01166d923a6b261b52d289095cd73afbdabda2e73c9a9237d660"
    fechS.vm.box_download_checksum_type = "sha256"
    fechS.vm.hostname = "fech-chaS"
    fechS.vm.provider :virtualbox do |vb|
      vb.name = "fech-chaS_vb"

      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
    end

    # keep SSH connection alive
    fechS.ssh.keep_alive = true

    # ignore Vagrantfiles (if any) found inside a box   
    fechS.vm.ignore_box_vagrantfile = true
    fechS.vm.box_check_update = false
    # allow Vagrant to modify etc/hosts file during provisioning, This can be useful for ensuring that your host machine can easily resolve the guest machine's hostname without needing to manually edit the /etc/hosts file, also allow VMs to communicate with eachother
    fechS.vm.allow_hosts_modification = true
    fechS.vm.network "private_network", ip: "192.168.56.110"
    fechS.vm.provision "shell", path: "scripts/bootstrap_vm1.sh"
  end
end