MASTER_NAME = "fech-chaS"
VB_NAME = "fech-chaS_vb"
VM_PROVIDER = "virtualbox"
MASTER_IP = "192.168.56.110"
BOX = "ubuntu/jammy64"
BOX_VERSION = "20241002.0.0"
MEMORY =  2048
CPU = 1

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.vm.box_version = BOX_VERSION
    config.vm.provider VM_PROVIDER do |vb|
        vb.name = VB_NAME
        vb.memory = MEMORY
        vb.cpus = CPU
        vb.gui = false
    end
    config.vm.define MASTER_NAME do |master|
        master.vm.hostname = MASTER_NAME
        master.vm.network "private_network", ip: WORKER_IP
        master.vm.provision "shell", path: "scripts/bootstrap_vm1.sh"
        # allow Vagrant to modify etc/hosts file during provisioning, This can be useful for ensuring that your host machine can easily resolve the guest machine's hostname without needing to manually edit the /etc/hosts file, also allow VMs to communicate with eachother
        master.vm.allow_hosts_modification = true
    end
end