Vagrant.configure("2") do |config|
    #Server Node
    config.vm.define "amiskiS" do |server_conf|
        server_conf.vm.box = "hashicorp/bionic64"
        server_conf.vm.box_version = "1.0.282"
        server_conf.vm.hostname = "Server"
        server_conf.vm.network "private_network", ip: "192.168.56.110"
        server_conf.vm.provider "virtualbox" do |vb|
            vb.name = "amiskiS"
            vb.memory = "1024"
            vb.cpus = 1
        end
        server_conf.vm.provision "shell", path: "./scripts/vm1_setup.sh"
    end
    #Worker Node
    config.vm.define "amiskiWS" do |worker_conf|
        worker_conf.vm.box = "hashicorp/bionic64"
        worker_conf.vm.box_version = "1.0.282"
        worker_conf.vm.hostname = "ServerWorker"
        worker_conf.vm.network "private_network", ip: "192.168.56.111"
        worker_conf.vm.provider "virtualbox" do |vb|
            vb.name = "amiskiWS"
            vb.memory = "512"
            vb.cpus = 1
        end
        worker_conf.vm.provision "shell", path: "./scripts/vm2_setup.sh"
    end
end

  