MASTER_NAME = "aboudounS"
WORKER_NAME = "aboudounSW"
VM_PROVIDER = "virtualbox"
BOX = "ubuntu/jammy64"
BOX_VERSION = "20241002.0.0"
MEMORY =  2048
CPU = 1
MASTER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
    # Specify the base box and version
    config.vm.box = BOX
    config.vm.box_version = BOX_VERSION
    # keep SSH connection alive
    config.ssh.keep_alive = true

    config.vm.provider VM_PROVIDER do |vb|
        vb.memory = MEMORY
        vb.cpus = CPU
        vb.gui = false
    end
    # Master VM configuration
    config.vm.define MASTER_NAME do |master|
        master.vm.hostname = MASTER_NAME
        master.vm.network "private_network", ip: MASTER_IP
        master.vm.provision "shell", path: "scripts/bootstrap_vm1.sh"
    end
    # Worker VM configuration
    config.vm.define WORKER_NAME do |worker|
        worker.vm.hostname = WORKER_NAME
        worker.vm.network "private_network", ip: WORKER_IP
        worker.vm.provision "shell", path: "scripts/bootstrap_vm2.sh"
    end

end

