Vagrant.configure("2") do |config|
    config.vm.define "amiskiS" do |server_conf|
        server_conf.vm.box = "ubuntu/jammy64"
        # server_conf.vm.box_version = "1.0.282"
        server_conf.vm.hostname = "Server"
        server_conf.vm.network "private_network", ip: "192.168.56.110"
        server_conf.vm.provider "virtualbox" do |vb|
            vb.name = "amiskiS"
            vb.memory = "1048"
            vb.cpus = 1
        end
        server_conf.vm.provision "shell", path: "./scripts/vm_setup.sh"
    end
end

